;; (setq linum-delay t)
;; (defadvice linum-schedule (around my-linum-schedule () activate)
;;   (run-with-idle-timer 0.2 nil #'linum-update-current))
;;(setq linum-format "%4d")
;; (global-linum-mode )
;; (hlinum-activate)
